---
name: Ansible Molecule
description: Run Ansible Molecule
author: Michael Schmitz

inputs:
  ansible_version:
    description: Ansible version to use, leave empty for newest
    default: ''
  distro:
    description: 'Execute tests against distribution'
    default: 'debian-12'
  molecule_scenario:
    description: Molecule scenario for testing
    default: 'hetznercloud'
  molecule_version:
    description: Molecule version to use, leave empty for newest
    default: ''
  python_version:
    description: Python version to use
    default: '3.x'
  jinja2_version:
    description: Jinaj2 version to use, leave empty for newest
    default: ''
  test_type:
    description: 'Choose between: unit|integration'
    default: 'unit'
  token:
    description: 'Gitea Runner token'
    default: 'unit'

runs:
  using: "composite"
  steps:
    - name: Check out the molecule repository
      uses: actions/checkout@v4
      with:
        github-server-url: 'https://gitea.msqu.de'
        repository: ansible/molecule
        token: ${{ inputs.token }}
        path: 'git_molecule'
        ref: 'main'

    - name: Set CI_HOSTNAME
      run: echo "CI_HOSTNAME=$(echo $MOLECULE_DISTRO | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      shell: bash
      env:
        MOLECULE_DISTRO: "${{ inputs.distro }}"

    - name: Set CI_PROJECT_NAME_MOLECULE
      run: echo "CI_PROJECT_NAME_MOLECULE=$(echo $GITHUB_REPOSITORY_OWNER | tr '_' '-')" >> $GITHUB_ENV
      shell: bash

    - name: Prepare Ansible Vault
      run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > "$GITHUB_WORKSPACE/.vault"
      shell: bash

    - name: Prepare SSH Key / Config
      run: |
        mkdir -p ~/.ssh/ && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        eval "$(ssh-agent -s)" && echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - >/dev/null
      shell: bash

    ### test until here
    - name: Prepare Molecule Scenario
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/molecule/default
        rsync -avzh --ignore-existing --ignore-errors git_molecule/scenarios/$MOLECULE_SCENARIO_NAME/ ${GITHUB_WORKSPACE}/molecule/default/
      shell: bash
      env:
        MOLECULE_SCENARIO_NAME: "${{ inputs.molecule_scenario }}"

    - name: Sync test vars
      run: if [[ "$TEST_TYPE" == "unit" ]] && [[ -f "${GITHUB_WORKSPACE}/tests/vars.yml" ]]; then mkdir -p ${GITHUB_WORKSPACE}/molecule/default/group_vars/all/ && rsync -aP ${GITHUB_WORKSPACE}/tests/vars.yml ${GITHUB_WORKSPACE}/molecule/default/group_vars/all/test_vars.yml; fi
      shell: bash
      env:
        TEST_TYPE: "${{ inputs.test_type }}"

    - name: Install software for generic use case
      run: pip install 'ansible-core${{ inputs.ansible_version }}' 'molecule${{ inputs.molecule_version }}' molecule-plugins[docker] docker netaddr jmespath dnspython 'Jinja2${{ inputs.jinja2_version }}'
      shell: bash

    - name: Pip list
      run: pip list
      shell: bash

    - name: Install collections from collections.yml
      if: "${{ inputs.ansible_scenario != '' }}"
      run: ansible-galaxy install -r git_molecule/requirements/collections_${{ inputs.ansible_scenario }}.yml
      shell: bash

    - name: Print molecule version infos
      run: molecule --version
      shell: bash

    - name: Print installed ansible collections
      run: ansible-galaxy collection list
      shell: bash

    - name: Run Molecule tests
      run: molecule test
      shell: bash
      env:
        ANSIBLE_FORCE_COLOR: '1'
        ANSIBLE_VERBOSITY: '2'
        CI_JOB_ID: "${{ github.run_id }}"
        MOLECULE_DEBUG: '1'
        MOLECULE_DISTRO: "${{ inputs.distro }}"
        MOLECULE_SCENARIO_NAME: "${{ inputs.molecule_scenario }}"
        PY_COLORS: '1'
        TEST_TYPE: "${{ inputs.test_type }}"
